/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica;

import java.awt.Color;
import java.text.SimpleDateFormat;

/**
 *
 * @author NATHALY
 */
public class PANEL extends javax.swing.JFrame {

    /**
     * Creates new form PANEL
     */
    public PANEL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AGRUPARRBTN = new javax.swing.ButtonGroup();
        PANELVIOLETA = new javax.swing.JPanel();
        CHKEXCELENTE = new javax.swing.JCheckBox();
        CHKBUENO = new javax.swing.JCheckBox();
        CHKMALO = new javax.swing.JCheckBox();
        BTNMOSTRAR = new javax.swing.JButton();
        RBFEMENINO = new javax.swing.JRadioButton();
        RBMASCULINO = new javax.swing.JRadioButton();
        CAMBIO = new javax.swing.JButton();
        PANELAZUL = new javax.swing.JPanel();
        LBLTITULO = new javax.swing.JLabel();
        PANELCELESTE = new javax.swing.JPanel();
        LBLPERRITO = new javax.swing.JLabel();
        BTNSUMAR = new javax.swing.JButton();
        INGRESOSUMA = new javax.swing.JTextField();
        TBTNCAMBIAR = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SALIDA = new javax.swing.JTextArea();
        CBBTIPO = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LISTOPOCION = new javax.swing.JList<>();
        SLIDER = new javax.swing.JSlider();
        PROGRESO = new javax.swing.JProgressBar();
        CONTRASEÑA = new javax.swing.JPasswordField();
        CONTADOR = new javax.swing.JSpinner();
        INGRESOFECHA = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        PANELVIOLETA.setBackground(new java.awt.Color(204, 204, 255));

        CHKEXCELENTE.setText("EXCELENTE");

        CHKBUENO.setText("BUENO");

        CHKMALO.setText("MALO");
        CHKMALO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHKMALOActionPerformed(evt);
            }
        });

        BTNMOSTRAR.setText("MOSTRAR");
        BTNMOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMOSTRARActionPerformed(evt);
            }
        });

        AGRUPARRBTN.add(RBFEMENINO);
        RBFEMENINO.setText("FEMENINO");

        AGRUPARRBTN.add(RBMASCULINO);
        RBMASCULINO.setText("MASCULINO");

        CAMBIO.setText("IR");
        CAMBIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMBIOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANELVIOLETALayout = new javax.swing.GroupLayout(PANELVIOLETA);
        PANELVIOLETA.setLayout(PANELVIOLETALayout);
        PANELVIOLETALayout.setHorizontalGroup(
            PANELVIOLETALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELVIOLETALayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PANELVIOLETALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RBMASCULINO)
                    .addComponent(RBFEMENINO)
                    .addComponent(CHKMALO, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PANELVIOLETALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CHKEXCELENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(CHKBUENO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BTNMOSTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(CAMBIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PANELVIOLETALayout.setVerticalGroup(
            PANELVIOLETALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELVIOLETALayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CHKEXCELENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHKBUENO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHKMALO)
                .addGap(18, 18, 18)
                .addComponent(RBFEMENINO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBMASCULINO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CAMBIO, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BTNMOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        PANELAZUL.setBackground(new java.awt.Color(102, 102, 255));

        LBLTITULO.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        LBLTITULO.setText("PROYECTO INF 121 ");

        javax.swing.GroupLayout PANELAZULLayout = new javax.swing.GroupLayout(PANELAZUL);
        PANELAZUL.setLayout(PANELAZULLayout);
        PANELAZULLayout.setHorizontalGroup(
            PANELAZULLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELAZULLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LBLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PANELAZULLayout.setVerticalGroup(
            PANELAZULLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELAZULLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LBLTITULO, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        PANELCELESTE.setBackground(new java.awt.Color(153, 204, 255));

        LBLPERRITO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/perrito.png"))); // NOI18N

        BTNSUMAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/2.png"))); // NOI18N
        BTNSUMAR.setText("SUMAR");
        BTNSUMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSUMARActionPerformed(evt);
            }
        });

        INGRESOSUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESOSUMAActionPerformed(evt);
            }
        });

        TBTNCAMBIAR.setText("CAMBIAR");
        TBTNCAMBIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBTNCAMBIARActionPerformed(evt);
            }
        });

        SALIDA.setColumns(20);
        SALIDA.setRows(5);
        jScrollPane1.setViewportView(SALIDA);

        CBBTIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERRO", "GATO", "LORO" }));

        LISTOPOCION.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SI", "NO", "TALVEZ" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(LISTOPOCION);

        SLIDER.setMinorTickSpacing(25);

        PROGRESO.setForeground(new java.awt.Color(255, 51, 51));

        CONTADOR.setModel(new javax.swing.SpinnerNumberModel(0, 0, 18, 1));

        javax.swing.GroupLayout PANELCELESTELayout = new javax.swing.GroupLayout(PANELCELESTE);
        PANELCELESTE.setLayout(PANELCELESTELayout);
        PANELCELESTELayout.setHorizontalGroup(
            PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELCELESTELayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANELCELESTELayout.createSequentialGroup()
                        .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TBTNCAMBIAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNSUMAR, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(INGRESOSUMA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SLIDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANELCELESTELayout.createSequentialGroup()
                                .addComponent(CBBTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addComponent(INGRESOFECHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PANELCELESTELayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBLPERRITO, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CONTADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
            .addComponent(PROGRESO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PANELCELESTELayout.setVerticalGroup(
            PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELCELESTELayout.createSequentialGroup()
                .addComponent(PROGRESO, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANELCELESTELayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CONTADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PANELCELESTELayout.createSequentialGroup()
                        .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(INGRESOSUMA)
                            .addComponent(BTNSUMAR, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(CBBTIPO))
                        .addGap(18, 18, 18)
                        .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBTNCAMBIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SLIDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INGRESOFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PANELCELESTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANELCELESTELayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(LBLPERRITO, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(PANELCELESTELayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANELVIOLETA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PANELCELESTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PANELAZUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PANELAZUL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANELCELESTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PANELVIOLETA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSUMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSUMARActionPerformed
        String ingre=this.INGRESOSUMA.getText();
        int conv=Integer.parseInt(ingre)+1;
        String c=String.valueOf(conv);
        this.INGRESOSUMA.setText(c);
        //this.INGRESOSUMA.setText((Integer.parseInt(this.INGRESOSUMA.getText())+1)+"");
    }//GEN-LAST:event_BTNSUMARActionPerformed

    private void INGRESOSUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESOSUMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INGRESOSUMAActionPerformed

    private void TBTNCAMBIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBTNCAMBIARActionPerformed
        if(this.TBTNCAMBIAR.isSelected())
        {
            this.PANELVIOLETA.setBackground(Color.red);
        }
        else
        {
            this.PANELVIOLETA.setBackground(Color.white);
        }
    }//GEN-LAST:event_TBTNCAMBIARActionPerformed

    private void CHKMALOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHKMALOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHKMALOActionPerformed

    private void BTNMOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMOSTRARActionPerformed
        //CHKBOX
        String datos="";
        if(CHKEXCELENTE.isSelected())
        {
            datos="Excelente";
        }
        if(CHKBUENO.isSelected())
        {
            datos="bueno";
        }
        if(CHKMALO.isSelected())
        {
            datos="Malo";
        }
        //this.SALIDA.setText("\nLos datos fueron: "+datos);
        this.SALIDA.append("\nLos datos fueron: "+datos);
        //RADIO BUTTON
        String genero="";
        genero+=DatosGenero();
        this.SALIDA.append("\nEs: "+genero);
        //CBBOX 
        String tipo="";
        tipo+="\nEs de tipo: "+DatosCCB();
        this.SALIDA.append(tipo);
        //LSITA
        String tipo2="";
        tipo2+="\nla opcion fue: "+Datoslista();
        this.SALIDA.append(tipo2);
        //Slider
        String b="";
        b+="\nEl porcentaje fue: "+Barrita();
         this.SALIDA.append(b);
        CArgarBarra();
        ///contraseña
        String c="";
        c+="\nla contraseña es: "+Contrasenia();
        this.SALIDA.append(c);
        //contador
        String cot="";
        cot+="\nla edad es: "+Contar();
        this.SALIDA.append(cot);
        ///CALENDARIP
        String fec="";
        fec+="\nLa fecha de nacimiento es: "+FecNac();
        this.SALIDA.append(fec);
    }//GEN-LAST:event_BTNMOSTRARActionPerformed

    private void CAMBIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMBIOActionPerformed
        OTRAVENTANA ot=new OTRAVENTANA();
        this.setVisible(false);
        ot.setVisible(true);
        System.out.println("HOLA A TODOS");
        
                
    }//GEN-LAST:event_CAMBIOActionPerformed
    private String FecNac()
    {
        SimpleDateFormat fecha=new SimpleDateFormat("dd/MM/yyyy");
        String fec="";
        fec=fecha.format(INGRESOFECHA.getDate());
        return fec;
    }
    private String Contar()
    {
        return this.CONTADOR.getValue()+"";
    }
    private String Contrasenia()
    {
        return this.CONTRASEÑA.getText();
    }
    private void CArgarBarra()
    {
        for(int i=0;i<101;i++)
        {
            this.PROGRESO.setValue(i*10);
        }
    }
    private String Barrita()
    {
        return this.SLIDER.getValue()+"";
    }
    private String Datoslista()
    {
        String dato="";
        dato=this.LISTOPOCION.getSelectedValue();
        return dato;
    }
    private String DatosCCB()
    {
        String dato="";
        dato=(String)this.CBBTIPO.getSelectedItem();
        return dato;
    }
    private String DatosGenero()
    {
        String genero="";
        if(RBFEMENINO.isSelected())
        {
            genero= this.RBFEMENINO.getText();
        }
        else if(RBMASCULINO.isSelected())
        {
            genero= this.RBMASCULINO.getText();
        }
        return genero;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANEL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AGRUPARRBTN;
    private javax.swing.JButton BTNMOSTRAR;
    private javax.swing.JButton BTNSUMAR;
    private javax.swing.JButton CAMBIO;
    private javax.swing.JComboBox<String> CBBTIPO;
    private javax.swing.JCheckBox CHKBUENO;
    private javax.swing.JCheckBox CHKEXCELENTE;
    private javax.swing.JCheckBox CHKMALO;
    private javax.swing.JSpinner CONTADOR;
    private javax.swing.JPasswordField CONTRASEÑA;
    private com.toedter.calendar.JDateChooser INGRESOFECHA;
    private javax.swing.JTextField INGRESOSUMA;
    private javax.swing.JLabel LBLPERRITO;
    private javax.swing.JLabel LBLTITULO;
    private javax.swing.JList<String> LISTOPOCION;
    private javax.swing.JPanel PANELAZUL;
    private javax.swing.JPanel PANELCELESTE;
    private javax.swing.JPanel PANELVIOLETA;
    private javax.swing.JProgressBar PROGRESO;
    private javax.swing.JRadioButton RBFEMENINO;
    private javax.swing.JRadioButton RBMASCULINO;
    private javax.swing.JTextArea SALIDA;
    private javax.swing.JSlider SLIDER;
    private javax.swing.JToggleButton TBTNCAMBIAR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
